# General
FPS = 60

# Window
WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 900
WINDOW_TITLE = "Pacman"
CONTENT_START_X = 100
CONTENT_END_X = 900
CONTENT_START_Y = 130
CONTENT_END_Y = 800

# Assets
SPRITES_SHEET_PATH = "assets/sprites_sheet.png"
FONT_PATH = "assets/Emulogic-zrEw.ttf"

# Sprites
SPRITES_WIDTH = 448
SPRITES_HEIGHT = 480
SPRITE_COLUMN_WIDTH = 32
SPRITE_ROWS_HEIGHT = 32
SPRITE_COLUMNS_COUNT = 14
SPRITE_ROWS_COUNT = 13
FRAME_SLOWER = 5

# Welcome
WELCOME_TEXT = "Press space to continue."

# Game
MAX_MAZE_SIZE = 560
WALLS_COLOR = (255, 255, 255)
SPEED = 4.0  # Squares per second
GHOST_FRIGHTENED_DURATION = 8.0
GHOST_RESPAWN_DELAY = 5.0
