# General
FPS = 60

# Window
WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 1500
WINDOW_TITLE = "Pacman"
CONTENT_START_X = 100
CONTENT_END_X = 900
CONTENT_START_Y = 300
CONTENT_END_Y = 1400

# Assets
SPRITES_SHEET_PATH = "assets/sprites_sheet.png"
FONT_PATH = "assets/Emulogic-zrEw.ttf"

# Sprites
SPRITES_WIDTH = 448
SPRITES_HEIGHT = 480
SPRITE_COLUMN_WIDTH = 32
SPRITE_ROWS_HEIGHT = 32
SPRITE_COLUMNS_COUNT = 14
SPRITE_ROWS_COUNT = 13
FRAME_SLOWER = 5

# Welcome
WELCOME_TEXT = "Press space to continue."

# Game
MAX_MAZE_SIZE = 800
WALLS_COLOR = (255, 255, 255)
SPEED = 7.5  # Squares per second
