# General
FPS = 60

# Window
WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 1500
WINDOW_TITLE = "Pacman"
CONTENT_START_X = 100
CONTENT_END_X = 900
CONTENT_START_Y = 300
CONTENT_END_Y = 1400

# Sprites
SPRITES_SHEET_PATH = "assets/sprites_sheet.png"
SPRITES_WIDTH = 448
SPRITES_HEIGHT = 480
SPRITE_COLUMN_WIDTH = 32
SPRITE_ROWS_HEIGHT = 32
SPRITE_COLUMNS_COUNT = 14
SPRITE_ROWS_COUNT = 13

# Pages

# Welcome
WELCOME_TEXT = "Press space to continue."

# Scores
SCORES_PATH = "data/scores.json"
